### PR TITLE
ECO-672 change quiz fail thank you message

### PR DESCRIPTION
**Pull request by liorama**

### CODE REVIEW

**Comment by nitzantomer** [comment]
didn't we say that there should be padding in curly brackets?
that is: 
`);`
and:
`{ SuccessBasedThankYou.diamondElements }`

**Comment by liorama** [comment]
@nitzantomer Yes!  This is not my normal laptop so I'm rebuilding my IDE style guide as I go.

**Comment by nitzantomer** [comment]
ok, so better to fix it, but it's approved

**Comment by doodyparizada** [comment]
> @nitzantomer Yes! This is not my normal laptop so I'm rebuilding my IDE style guide as I go. It's still "fixing" me to the wrong style.

@liorama just import the style from our marketplace projec: thttps://github.com/kinecosystem/marketplace-server/blob/master/code_style_scheme.xml

**Comment by liorama** [comment]
Imported and Fixed. @doodyparizada that style guide has a few things wrong, the padding @nitzantomer was talking about is one of them (others were mostly HTML styles). I fixed it and will commit. It still aligns wrapped lines with spaces which is bad, I couldn't resolve that but I'll keep at it.

**Pull request merged**
